from dataclasses import dataclass


@dataclass
class OutputGenerationArguments:
    """
    Arguments used for function that generates output file.
    """
    # Path to correct solution executable
    correct_solution_exe: str
    # Path to input file
    input_test: str
    # Path to output file
    output_test: str


@dataclass
class OutputVerificationArguments:
    """
    Arguments used for function that verifies an output file which wasn't generated by sinol-make.
    """
    # Path to input file
    input_test: str
    # Path to the verified output file
    output_test: str
    # Path to the output file generated by the correct solution
    model_output_test: str
