name: pytest-arch
run-name: Run pytest on Arch Linux
on:
  push:
    branches: 'main'
  pull_request:
jobs:
  pytest:
    runs-on: self-hosted
    strategy:
        matrix:
            python-version: ["3.10.18", "3.13.5"]
    name: pytest-arch-python-${{ matrix.python-version }}
    container:
      image: archlinux:latest
      volumes:
        - /home/actions/oiejq:/github/home/.local/bin
      options:
        --privileged
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Prepare system
        run: |
          sysctl kernel.perf_event_paranoid=-1
          pacman -Syu --noconfirm diffutils time gcc dpkg ghostscript texlive-latexextra git
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          pip3 install .[tests]
      - name: Run pytest
        env:
          PYTEST_ADDOPTS: "--color=yes"
        run: |
          python3 -m pytest -v -n $((`nproc` / 2))
