name: pytest-arch
run-name: Run pytest on Arch Linux
on: [push]
jobs:
  pytest:
    runs-on: self-hosted
    strategy:
        matrix:
            python-version: ["3.7.17", "3.12.0"]
    name: pytest-arch-python-${{ matrix.python-version }}
    container:
      image: archlinux:latest
      options:
        --privileged
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Prepare system
        run: |
          sysctl kernel.perf_event_paranoid=-1
          pacman -Syu --noconfirm gcc dpkg ghostscript texlive-latexextra wget
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          pip3 install .[tests]
          mkdir -p ~/.local/bin
          wget -O ~/.local/bin/ https://github.com/sio2project/sio2jail/releases/download/v1.4.4/sio2jail
      - name: Run pytest
        env:
          PYTEST_ADDOPTS: "--color=yes"
        run: |
          python3 -m pytest -v
