name: pytest
run-name: Run pytest
on: [push, pull_request]
jobs:
  pytest:
    runs-on: self-hosted
    container:
      image: ubuntu:latest
      volumes:
        - /home/actions/oiejq:/root/.local/bin
      env:
        DEB_PYTHON_INSTALL_LAYOUT: deb
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Prepare system
        run: |
          apt update
          export TZ=Europe/Warsaw
          ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
      - name: Set up Python 3.11
        run: |
          apt install -y python3.11 python3.11-dev python3-pip
          pip3 install -U setuptools
          echo $DEB_PYTHON_INSTALL_LAYOUT
      - name: Install dependencies
        run: |
          pip3 install .[tests]
      # - name: Install oiejq
      #   run: |
      #     wget https://oij.edu.pl/zawodnik/srodowisko/oiejq.tar.gz
      #     mkdir -p ~/.local/bin
      #     tar -xzf oiejq.tar.gz -C ~/.local/bin --strip-components=1
      - name: Run pytest
        run: |
          python3 -m pytest
