name: pytest
run-name: Run pytest
on: [push, pull_request]
jobs:
  pytest:
    runs-on: self-hosted
    steps:
      - name: Clear repository
        run: rm -fr $GITHUB_WORKSPACE && mkdir $GITHUB_WORKSPACE
      - name: Checkout
        uses: actions/checkout@v2
      - name: Prepare system
        run: |
          apt update
          apt install -y software-properties-common wget
      - name: Set up Python 3.11 and pip
        run: |
          add-apt-repository ppa:deadsnakes/ppa
          apt update
          apt install -y python3.11 python3-pip
      - name: Install dependencies
        run: |
          pip3 install .[tests]
      - name: Install oiejq
        run: |
          wget https://oij.edu.pl/zawodnik/srodowisko/oiejq.tar.gz
          mkdir -p ~/.local/bin
          tar -xzf oiejq.tar.gz -C ~/.local/bin --strip-components=1
      - name: Run pytest
        run: |
          pytest
