name: pytest
run-name: Run pytest
on: [push, pull_request]
jobs:
  pytest:
    runs-on: self-hosted
    container:
      image: ubuntu:latest
      options:
        --network host
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Prepare system
        run: |
          apt update
          apt install -y software-properties-common
          export TZ=Europe/Warsaw
          ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
      - name: Set up Python 3.11 and pip
        run: |
          apt install -y wget build-essential libncursesw5-dev libssl-dev libsqlite3-dev tk-dev libgdbm-dev libc6-dev libbz2-dev libffi-dev zlib1g-dev
          add-apt-repository ppa:deadsnakes/ppa
          apt update
          apt install -y python3.11 python3-pip
      - name: Install dependencies
        run: |
          pip3 --default-timeout=100 install .[tests]
      - name: Install oiejq
        run: |
          wget https://oij.edu.pl/zawodnik/srodowisko/oiejq.tar.gz
          mkdir -p ~/.local/bin
          tar -xzf oiejq.tar.gz -C ~/.local/bin --strip-components=1
      - name: Run pytest
        run: |
          pytest
